workflows:
  react-native-android-release:
    name: React Native Android Release
    environment:
      node: 18
      java: 17
      groups:
        - expo_credentials  # contains EXPO_TOKEN, KEYSTORE, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD
    scripts:
      - name: Decode keystore (local + CI safe)
        script: |
          # Determine target path
          TARGET_DIR="${CM_BUILD_DIR:-$(pwd)}/android/app"
          mkdir -p "$TARGET_DIR"

          # Only decode if KEYSTORE is set
          if [ -n "$KEYSTORE" ]; then
            echo "Decoding keystore to $TARGET_DIR/dollabills.jks"
            echo "$KEYSTORE" | base64 --decode > "$TARGET_DIR/dollabills.jks"
          else
            echo "No KEYSTORE variable found — skipping decode."
          fi
      - name: Install dependencies
        script: npm install
      - name: Run tests
        script: npm test || echo "No tests"
      - name: Build Android APK with EAS
        script: npx eas-cli build --platform android --profile production --non-interactive
    artifacts:
      - dist/*.apk
      - dist/*.aab
