workflows:
  react-native-android-release:
    name: React Native Android Release
    environment:
      node: 18
      java: 17
      groups:
        - expo_credentials       # contains EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Authenticate with Expo
        script: npx eas-cli login --token $EXPO_TOKEN
      - name: Run tests
        script: npm test || echo "No tests"
      - name: Build Android APK with EAS
        script: npx eas-cli build --platform android --non-interactive --profile production
    artifacts:
      - dist/*.apk
    publishing:
      email:
        recipients:
          - $CM_EMAIL
