workflows:
  react-native-android-release:
    name: React Native Android Release
    environment:
      node: 18
      java: 17
      groups:
        - expo_credentials
    scripts:
      - name: Decode keystore
        script: |
          echo $KEYSTORE | base64 --decode > ~/termuxorchestrator/dollabills.jks
      - name: Install dependencies
        script: npm install
      - name: Run tests
        script: npm test || echo "No tests"
      - name: Build Android APK with EAS
        script: npx eas-cli build --platform android --profile production --non-interactive
    artifacts:
      - dist/*.apk
      - dist/*.aab
